### ISSUE TITLE
Play well with other SPI devices

### ISSUE THREAD

**Issue by thinkyhead** [greiman/SdFat-beta#1]
Developers like myself over at https://github.com/MarlinFirmware/Marlin/issues/1226 are scratching our heads how to get SD card reading to work alongside SPI-driven thermocouples and other SPI devices. I'm not personally familiar with the use of chip-select lines, or whether these other devices are designed to play well on SPI buses either, but perhaps you can provide some insight to guide us in the right direction....?

https://github.com/MarlinFirmware/Marlin/issues/1227

**Comment by greiman** [comment]
https://learn.sparkfun.com/tutorials/serial-peripheral-interface-spi

**Comment by thinkyhead** [comment]
Studying your code is also very helpful, thanks!
