### ISSUE TITLE
Card doesnt Sleep after writing on it

### ISSUE THREAD

**Issue by kalaveras** [greiman/SdFat-beta#14]
My hardware is a atmega644PA and i use the SPI hardware module that it has. 
I upload the code with Arduino IDE and ad-hoc third party board implemented by my self.

I only use a SD in the SPI. It doesnt have any hardware Pull-ups on spi lines.

I use this library in order to allow a micro SD to go to Sleep mode with low consumption.

If I SD.begin() the SD, it consumes 250 uA, so i assume it goes to sleep mode correctly. 

The issue is that when I write something on a file, (open file, write on it, close file) the card consumes around 14 mA permanently. Even after a while. So probably the SD blocks on same state and doent allow it to sleep. I can write again whitout problems.

I solve it calling SD.begin function after "close file". 
But this is just a temporal patch.  Probably the problem is in some of the code that SdSpiCard::begin function does and the file write code doesnt. I dont know sd specs to go deeply to solve it.

**Comment by greiman** [comment]
If you are using  the official SD.h library, I don't maintain it.

It has had the sleep bug since it was written in 2009 and the Arduino company has not fixed it.
