### ISSUE TITLE
Possible rtc

### ISSUE THREAD

**Issue by delchrys** [greiman/SdFat-beta#18]
Hi i made a project based on this lowlatencylogger and combined it with reading a mma8451 accelerometer sensor instead of mpu4050. Do you know if it is possible to add a timestamp to the data with an rtf. I don't know if they are fast enough. But I like to add real time to my data. My recording are at 50ms . Like to know what my options are. Maybe data time + micros every minute or so. So only polling the rtc every minute.

**Comment by greiman** [comment]
Closed, this version of SdFat-beta is no longer supported.
