### ISSUE TITLE
sharing SPI with another device

### ISSUE THREAD

**Issue by satcr** [greiman/SdFat-beta#20]
Sir,
I am using low latency data logger code of yours. But I want to share the SPI with another device (2.7V 12-Bit A/D Converter with SPI™ Serial Interface). My requirement is to read from this ADC and log it to SD cad. But when I tie my MISO pins to share SPI, my read from SD and reads from ADC doesn't work. voltage on this Miso pin goes to some steady 3.3v, its not pulsing according to data. so my adc reads are showing 4096 (all high) and  My SD cad reads are failing.This happens only when I tie MISO ins together.  Is it because of clock speed issues? I understand that SD cad writes are happening at much faster rate, but for ADC this speed has to be reduced. how to solve this issue? I am sing Arduino Mega and a  Micro Sd Card Module to connect SD card.

**Comment by greiman** [comment]
Closed, this version of SdFat-beta is no longer supported.
