### ISSUE TITLE
Reporting erased state of card

### ISSUE THREAD

**Issue by gbhug5a** [greiman/SdFat-beta#31]
Would you consider reporting the value of the DATA_STAT_AFTER_ERASE bit (bit 55) of the SCR register in SDInfo.ino?  This is the erased state of the flash memory, which can differ among manufacturers.  This would require adding support for ACMD51 to the library source, or possibly  erasing a block and reading back the first byte.

**Comment by greiman** [comment]
I put this on my to do list.   I need to finish a set of features that allow USB drives and more flexible software SPI. 

You can determine the DATA_STAT_AFTER_ERASE bit by running the SdFormatter example.  Select the E or F option and the erase value will be printed.


```
Enter option: F

Erasing
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................
All data set to 0x00
```

**Comment by gbhug5a** [comment]
Very good.  Thanks very much.
