### ISSUE TITLE
Missing define?

### ISSUE THREAD

**Issue by WereCatf** [greiman/SdFat-beta#4]
SdSpiSTM32F1.cpp references both SPI_DMAC_RX_CH and SPI_DMAC_TX_CH, but neither of those are defined. There are defines for SPI1_DMAC_RX_CH and SPI1_DMAC_TX_CH, but I'm not entirely up to snuff on the DMA-stuff yet and I'm not sure if it's just a typo or something else.

**Comment by greiman** [comment]
This file is for Arduino STM32 and is out of date.  They have not sent me a pull request.

[Here](https://github.com/victorpv/SdFat/blob/master/SdFat/SdSpiSTM32F1.cpp) is their current version.  It won't work with SdFat-beta.
