### ISSUE TITLE
possibility of stream iterator implementation?

### ISSUE THREAD

**Issue by ripe909** [greiman/SdFat-beta#44]
I am trying to use SDfat streams with a serializer (ThorsSerializer), which uses stream iterators to parse out strings during deserialization.

specifically here:  https://github.com/Loki-Astari/ThorsSerializer/blob/master/src/Serialize/JsonManualLexer.cpp#L157

I suppose this would also be tied to a full implementation of stdlib functions, or using a full distribution of stdlib (newlib on ARM) instead of the minimal implementation in SdFat.   

With Teensy 4 and more powerful MCUs it shouldn't be as much of a problem to use full stdlib, but that is a different issue.

**Comment by greiman** [comment]
I can't help you. I get too many requests like this.
