### ISSUE TITLE
SdFatSdioEx no longer working.

### ISSUE THREAD

**Issue by JaredReabow** [greiman/SdFat-beta#47]
The new SD beta has dropped support for "SdFatSdioEx" and as a result sdEx, breaking most of my older projects which I want to port to teensy 4.1

**Comment by greiman** [comment]
Supporting SdFat has become a pain.  Paul offered a Teensy 4.1 but I didn't reply.

My Arduino Boards Manager in the IDE now lists 29 packages.

I only have a few of the possible URLS for board support packages in my IDE.  Look at this:

https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls

I suspect there are hundreds of "Arduino" like board support packages.  I have competing STM32 packages and can't support two or more STM32 systems. I get request for both.

I am overwhelmed by email.  I can't possibly continue to support SdFat.

By the way, the SdFatSdioEx functionality is now in the SdFat class.  See option one of the TeensySdioDemo.  The SdFat class supports FAT16/FAT32.  The SdFat class has the functionality of the old SdFat, SdFatEx, SdFatSdio, and SdFatSdioEx.

The other classes are SdExFat for exFAT files systems and SdFs for FAT16/FAT32 and exFAT file systems.
