### ISSUE TITLE
multiple SD cards

### ISSUE THREAD

**Issue by WMXZ-EU** [greiman/SdFat-beta#53]
I need to write sequentially to multiple SD cards (terra-byte data logger).

Any suggestions/examples?

IOW, is calling sd.begin with different ChipSelect save?

**Comment by greiman** [comment]
See this [old ](https://github.com/greiman/SdFat-beta/tree/master/examples/examplesV1/TwoCards)example.

**Comment by WMXZ-EU** [comment]
Thanks
