### ISSUE TITLE
hosting the documentation on a github.io page

### ISSUE THREAD

**Issue by jerabaul29** [greiman/SdFat-beta#59]
Do you think it would be possible to host your html files on a github.io page? It would make it much easier to browse :)

**Comment by greiman** [comment]
No, I find almost no one reads the documentation.  I wrote the first version of SdFat over ten years ago and a version was used in the official SD.h library.  

Most people just use the simplest open, print, close features.  I have tried to optimize SdFat so you don't need to know more and may even reduce performance by trying to optimize.

**Comment by jerabaul29** [comment]
Ok, thanks. So you actually advise to use the latest library, and not care myself about performance, but let the library take care of it, right? :)
