### ISSUE TITLE
LowLatency data logger won't compile ?

### ISSUE THREAD

**Issue by KingZogg** [greiman/SdFat-beta#6]
I did not write this code.
The author said that it ran fine on an UNO.
I tried on and UNO and a MO with the beta and the stable release.
Could you please have a quick look ?

[MPU6050RawLowLatencyLogger_MOD_DMP.zip](https://github.com/greiman/SdFat-beta/files/355878/MPU6050RawLowLatencyLogger_MOD_DMP.zip)

This is the Arduino forum link.
[http://forum.arduino.cc/index.php?topic=387305.0](url)

**Comment by greiman** [comment]
I don't debug mods to examples.

**Comment by KingZogg** [comment]
Understood.
Thanks anyway.
