### ISSUE TITLE
ARM Processor does not like the UserDataType.h file.

### ISSUE THREAD

**Issue by KingZogg** [greiman/SdFat-beta#7]
After much mucking around with my Adafruit feather M0
I got the MPU6050RawLowLatencyLogger.ino finally working.
Please change it to the following.
```

#ifndef UserDataType_h
#define UserDataType_h
struct data_t {
  unsigned long time;
  int16_t ax;
  int16_t ay;
  int16_t az;
  int16_t gx;
  int16_t gy;
  int16_t gz;
};
#endif  // UserDataType_h
```
as int ax; etc does NOT work with this processor.

**Comment by greiman** [comment]
Changed in the forum post
